// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AnkamaGames

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Manifest struct {
	_tab flatbuffers.Table
}

func GetRootAsManifest(buf []byte, offset flatbuffers.UOffsetT) *Manifest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Manifest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsManifest(buf []byte, offset flatbuffers.UOffsetT) *Manifest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Manifest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Manifest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Manifest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Manifest) Fragments(obj *Fragment, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Manifest) FragmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ManifestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ManifestAddFragments(builder *flatbuffers.Builder, fragments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fragments), 0)
}
func ManifestStartFragmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ManifestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
